"""removed migratetest integer feild to user

Revision ID: 0cd568c7c318
Revises: c00af3fd2d45
Create Date: 2024-04-08 13:18:16.504573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cd568c7c318'
down_revision = 'c00af3fd2d45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('migratetest')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('migratetest', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
