"""empty message

Revision ID: 205701c9ff28
Revises: 357abf68c5d6
Create Date: 2024-04-30 01:26:24.184828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '205701c9ff28'
down_revision = '357abf68c5d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=389),
               type_=sa.String(length=1000),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=389),
               existing_nullable=True)

    # ### end Alembic commands ###
