"""added to User model: ismode:boolean

Revision ID: 2cf43d2fa3ae
Revises: 9970bcb483e4
Create Date: 2024-04-18 12:13:56.914692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cf43d2fa3ae'
down_revision = '9970bcb483e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ismod', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('ismod')

    # ### end Alembic commands ###
