"""empty message

Revision ID: 357abf68c5d6
Revises: 831e356a9953
Create Date: 2024-04-30 01:20:41.520629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '357abf68c5d6'
down_revision = '831e356a9953'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('madeProfileAlready')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('madeProfileAlready', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
