"""Added unique constraint to RSVP model

Revision ID: 474342b9bcb6
Revises: 2cf43d2fa3ae
Create Date: 2024-04-22 17:17:15.126147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '474342b9bcb6'
down_revision = '2cf43d2fa3ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rsvp', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_rsvp_per_user_event', ['userID', 'eventID'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rsvp', schema=None) as batch_op:
        batch_op.drop_constraint('unique_rsvp_per_user_event', type_='unique')

    # ### end Alembic commands ###
