"""Removed many to many relation

Revision ID: 4d683edc4ded
Revises: 2f77530a25ca
Create Date: 2024-04-15 15:27:57.736646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d683edc4ded'
down_revision = '2f77530a25ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('flairone_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('flairtwo_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('flarirthree_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_event_flairone', 'flair', ['flairone_id'], ['flairID'])
        batch_op.create_foreign_key('fk_event_flairtwo', 'flair', ['flairtwo_id'], ['flairID'])
        batch_op.create_foreign_key('fk_event_flairthree', 'flair', ['flarirthree_id'], ['flairID'])
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_constraint('fk_event_flairthree', type_='foreignkey')
        batch_op.drop_constraint('fk_event_flairtwo', type_='foreignkey')
        batch_op.drop_constraint('fk_event_flairone', type_='foreignkey')
        batch_op.drop_column('flarirthree_id')
        batch_op.drop_column('flairtwo_id')
        batch_op.drop_column('flairone_id')
    op.create_table('flair_event_association',
                    sa.Column('event_id', sa.INTEGER(), nullable=False),
                    sa.Column('flair_id', sa.INTEGER(), nullable=False),
                    sa.ForeignKeyConstraint(['event_id'], ['event.eventID'], name='fk_event_id'),
                    sa.ForeignKeyConstraint(['flair_id'], ['flair.flairID'], name='fk_flair_id'),
                    sa.PrimaryKeyConstraint('event_id', 'flair_id')
                    )
    # ### end Alembic commands ###
