"""Drop RSVP table

Revision ID: 740f54002df4
Revises: a4d67ba37f9d
Create Date: 2024-04-28 15:08:43.967454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '740f54002df4'
down_revision = 'a4d67ba37f9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rsvp')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rsvp',
    sa.Column('rsvpID', sa.INTEGER(), nullable=False),
    sa.Column('userID', sa.INTEGER(), nullable=True),
    sa.Column('eventID', sa.INTEGER(), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['eventID'], ['event.eventID'], ),
    sa.ForeignKeyConstraint(['userID'], ['user.userid'], ),
    sa.PrimaryKeyConstraint('rsvpID'),
    sa.UniqueConstraint('eventID'),
    sa.UniqueConstraint('userID'),
    sa.UniqueConstraint('userID', 'eventID', name='unique_rsvp_per_user_event')
    )
    # ### end Alembic commands ###
