"""empty message

Revision ID: 9bcf48d32f9d
Revises: 831e356a9953
Create Date: 2024-04-25 16:07:39.224842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bcf48d32f9d'
down_revision = '831e356a9953'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('madeProfileAlready', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('pronouns', sa.String(length=40), nullable=False))
        batch_op.add_column(sa.Column('aboutMe', sa.String(length=500), nullable=False))
        batch_op.add_column(sa.Column('myMajor', sa.String(length=40), nullable=False))
        batch_op.add_column(sa.Column('academicYear', sa.String(length=40), nullable=False))
        batch_op.add_column(sa.Column('socialMediaLink', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('socialMediaLink')
        batch_op.drop_column('academicYear')
        batch_op.drop_column('myMajor')
        batch_op.drop_column('aboutMe')
        batch_op.drop_column('pronouns')
        batch_op.drop_column('madeProfileAlready')

    # ### end Alembic commands ###
