"""empty message

Revision ID: a7f7350f9197
Revises: 205701c9ff28
Create Date: 2024-05-03 15:19:09.570545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7f7350f9197'
down_revision = '205701c9ff28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rsvp')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rsvp',
    sa.Column('rsvpID', sa.INTEGER(), nullable=False),
    sa.Column('userID', sa.INTEGER(), nullable=True),
    sa.Column('eventID', sa.INTEGER(), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['eventID'], ['event.eventID'], ),
    sa.ForeignKeyConstraint(['userID'], ['user.userid'], ),
    sa.PrimaryKeyConstraint('rsvpID'),
    sa.UniqueConstraint('eventID'),
    sa.UniqueConstraint('userID'),
    sa.UniqueConstraint('userID', 'eventID', name='unique_rsvp_per_user_event')
    )
    # ### end Alembic commands ###
